//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhmStudio.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("OhmStudio.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel 的本地化字符串。
        /// </summary>
        public static string Common_Cancel {
            get {
                return ResourceManager.GetString("Common_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Clear 的本地化字符串。
        /// </summary>
        public static string Common_Clear {
            get {
                return ResourceManager.GetString("Common_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Close 的本地化字符串。
        /// </summary>
        public static string Common_Close {
            get {
                return ResourceManager.GetString("Common_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Delete 的本地化字符串。
        /// </summary>
        public static string Common_Delete {
            get {
                return ResourceManager.GetString("Common_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 InvertSelect 的本地化字符串。
        /// </summary>
        public static string Common_InvertSelect {
            get {
                return ResourceManager.GetString("Common_InvertSelect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No 的本地化字符串。
        /// </summary>
        public static string Common_No {
            get {
                return ResourceManager.GetString("Common_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 OK 的本地化字符串。
        /// </summary>
        public static string Common_OK {
            get {
                return ResourceManager.GetString("Common_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 SelectAll 的本地化字符串。
        /// </summary>
        public static string Common_SelectAll {
            get {
                return ResourceManager.GetString("Common_SelectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UnselectAll 的本地化字符串。
        /// </summary>
        public static string Common_UnselectAll {
            get {
                return ResourceManager.GetString("Common_UnselectAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Yes 的本地化字符串。
        /// </summary>
        public static string Common_Yes {
            get {
                return ResourceManager.GetString("Common_Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Current 的本地化字符串。
        /// </summary>
        public static string DateTimePicker_Current {
            get {
                return ResourceManager.GetString("DateTimePicker_Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Date 的本地化字符串。
        /// </summary>
        public static string DateTimePicker_Date {
            get {
                return ResourceManager.GetString("DateTimePicker_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Hour 的本地化字符串。
        /// </summary>
        public static string DateTimePicker_Hour {
            get {
                return ResourceManager.GetString("DateTimePicker_Hour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Midnight 的本地化字符串。
        /// </summary>
        public static string DateTimePicker_Midnight {
            get {
                return ResourceManager.GetString("DateTimePicker_Midnight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Minute 的本地化字符串。
        /// </summary>
        public static string DateTimePicker_Minute {
            get {
                return ResourceManager.GetString("DateTimePicker_Minute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Second 的本地化字符串。
        /// </summary>
        public static string DateTimePicker_Second {
            get {
                return ResourceManager.GetString("DateTimePicker_Second", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Time 的本地化字符串。
        /// </summary>
        public static string DateTimePicker_Time {
            get {
                return ResourceManager.GetString("DateTimePicker_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Today 的本地化字符串。
        /// </summary>
        public static string DateTimePicker_Today {
            get {
                return ResourceManager.GetString("DateTimePicker_Today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to hide password 的本地化字符串。
        /// </summary>
        public static string PasswordTextBox_HidePassword {
            get {
                return ResourceManager.GetString("PasswordTextBox_HidePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Click to show password 的本地化字符串。
        /// </summary>
        public static string PasswordTextBox_ShowPassword {
            get {
                return ResourceManager.GetString("PasswordTextBox_ShowPassword", resourceCulture);
            }
        }
    }
}
